pip_install_unittest_docstring_documentation_coverage:
    image: ubuntu:rolling
    script:
    - apt-get update -q
    - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-skimage python3-pytest python3-pytest-cov xvfb
    - apt-get install -qy python3-sympy --no-install-recommends
    - pip3 install --user .
    - xvfb-run -a python3 -m pytest --doctest-modules --cov=atomap atomap/
    - xvfb-run -a python3 -m pytest --doctest-glob="*.rst" doc/

style_checks_flake8:
    image: debian:sid
    script:
    - apt-get update -q
    - apt-get install -qy python3-flake8
    - python3 -m flake8 --exclude atomap/api.py atomap/

style_checks_flake8_docstrings:
    image: debian:sid
    script:
    - apt-get update -q
    - apt-get install -qy python3-flake8 python3-flake8-docstrings
    - python3 -m flake8 --exclude atomap/tests/ atomap/
    allow_failure: true

anaconda_install_tests:
    image: continuumio/anaconda3
    script:
    - apt-get install -qy libgl1-mesa-glx xvfb
    - conda install -c conda-forge hyperspy
    - conda install conda-build
    - mkdir build
    - conda build -c conda-forge --output-folder build .
    - conda install -c conda-forge build/linux-64/atomap-*.tar.bz2
    - xvfb-run python3 -m pytest --doctest-modules atomap/

pages_development_branch:
    image: ubuntu:rolling
    stage: deploy
    script:
    - apt-get update -q
    - apt-get install -qy python3-sphinx python3-sphinx-rtd-theme python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-traitlets python3-traits python3-natsort python3-sklearn python3-dill python3-ipython-genutils
    - apt-get install -qy python3-sympy --no-install-recommends
    - pip3 install --user .
    - cd doc
    - make html
    - cd ..
    - mv doc/_build/html pages_development
    artifacts:
        paths:
        - pages_development
    only:
    - master

pages:
    image: ubuntu:rolling
    stage: deploy
    script:
    - apt-get update -q
    - apt-get install -qy python3-sphinx python3-sphinx-rtd-theme python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-traitlets python3-traits python3-natsort python3-sklearn python3-dill python3-ipython-genutils
    - apt-get install -qy python3-sympy --no-install-recommends
    - apt-get remove -qy python3-matplotlib
    - pip3 install --user .
    - cd doc
    - make html
    - ls _build/html
    - cd ..
    - mv doc/_build/html public
    artifacts:
        paths:
        - public
    only:
    - release
