default:
    image: continuumio/miniconda3

run_tests:
    script:
    - conda install hyperspy pytest -c conda-forge -y
    - pip3 install -e .
    - python3 -m pytest --env nogui --doctest-modules atomap/
    - python3 -m pytest --env nogui --doctest-glob="*.rst" doc/

run_style_check:
    script:
    - conda install black -c conda-forge -y
    - python3 -m black atomap/ --diff --check --quiet
