default:
    image: continuumio/miniconda3

run_tests:
    script:
    - conda install hyperspy exspy pytest -c conda-forge -y
    - pip3 install -e .
    - python3 -m pytest --env nogui --doctest-modules atomap/
    - python3 -m pytest --env nogui --doctest-glob="*.rst" doc/

run_style_check:
    script:
    - conda install black -c conda-forge -y
    - python3 -m black atomap/ --diff --check --quiet

pages:
    stage: deploy
    rules:
        - if: '$CI_COMMIT_REF_NAME == "release"'
          when: on_success
        - when: never
    script:
    - apt update
    - apt-get install -qy --no-install-recommends build-essential xvfb xauth python3-pyqt5 texlive-latex-extra dvipng
    - conda install hyperspy sphinx sphinx_rtd_theme -c conda-forge -y
    - pip3 install .
    - cd doc/
    - bash make_all_documentation_images.sh
    - make html
    - cd ..
    - mv doc/_build/html public
    artifacts:
        paths:
        - public

pages_development:
    stage: deploy
    rules:
        - if: '$CI_COMMIT_REF_NAME == "master"'
          when: on_success
        - when: never
    script:
    - apt update
    - apt-get install -qy --no-install-recommends build-essential xvfb xauth python3-pyqt5 texlive-latex-extra dvipng
    - conda install hyperspy exspy sphinx sphinx_rtd_theme -c conda-forge -y
    - pip3 install .
    - cd doc/
    - bash make_all_documentation_images.sh
    - make html
    - cd ..
    - mv doc/_build/html public_development
    artifacts:
        paths:
        - public_development

