pip_install_tests:
    image: ubuntu:latest
    script: 
    - apt-get update -q
    - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-matplotlib python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-skimage
    - apt-get install -qy python3-sympy --no-install-recommends
    - pip3 install --upgrade pip
    - pip3 install --user .
    - python3 -m unittest discover

anaconda_install_tests:
    image: continuumio/anaconda3
    script:
    - conda install conda-build
    - mkdir build
    - conda build -c conda-forge --output-folder build .
    - conda install --use-local build/linux-64/atomap-*.tar.bz2
    - python3 -m unittest discover

pages:
    image: ubuntu:latest
    stage: deploy
    script: 
    - apt-get update -q
    - apt-get install -qy python3-sphinx python3-sphinx-rtd-theme python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-matplotlib python3-traitlets python3-traits python3-natsort python3-sklearn python3-dill python3-ipython-genutils
    - apt-get install -qy python3-sympy --no-install-recommends
    - pip3 install --user .
    - cd doc
    - make html
    - ls _build/html
    - cd ..
    - mv doc/_build/html public
    artifacts:
        paths:
        - public
    only:
    - release

