name: Documentation

on: [push, pull_request]

jobs:
  build_webpage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
      - name: Install ubuntu packages
        run: sudo apt-get install -qy --no-install-recommends build-essential xvfb xauth python3-pyqt5 texlive-latex-extra dvipng
      - name: Install conda-forge dependencies
        run: conda install pip hyperspy exspy ase sphinx sphinx_rtd_theme pytest -c conda-forge -y
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install
        run: pip install -e .
      - name: Making images
        run: |
          cd doc/
          bash make_all_documentation_images.sh
      - name: Building webpage
        run: |
          cd doc/
          sphinx-build -b html -d _build/doctrees   . _build/html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: doc/_build/html

  deploy:
      needs: build_webpage

      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
