name: Documentation

on: [push]

jobs:
  build_webpage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
      - name: Install ubuntu packages
        run: sudo apt-get install -qy --no-install-recommends build-essential xvfb xauth python3-pyqt5 texlive-latex-extra dvipng
      - name: Install conda-forge dependencies
        run: conda install pip hyperspy exspy ase sphinx sphinx_rtd_theme pytest -c conda-forge -y
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install
        run: pip install -e .
      - name: Making images
        run: |
          cd doc/
          bash make_all_documentation_images.sh
      - name: Building webpage
        run: |
          cd doc/
          sphinx-build -b html -d _build/doctrees   . _build/html
      - uses: actions/upload-artifact@v4
        with:
          path: doc/_build/html
