name: Lint and style check

on: [push, pull_request]

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--diff --check --quiet"
          src: "./atomap"
